name: dio_curl_interceptor
description: A Flutter package providing a Dio interceptor that logs HTTP requests as cURL commandsâ€”perfect for debugging, sharing, and reproducing requests. Includes a modern Flutter UI for viewing, filtering, exporting, and managing cached cURL logs
version: 3.0.2
homepage: https://github.com/venhdev/dio_curl_interceptor
repository: https://github.com/venhdev/dio_curl_interceptor

topics:
  - curl
  - dio
  - http
  - logging
  - console

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.5.0+1
  colored_logger: ^2.1.0
  codekit: ^0.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: any
  file_saver: any
  intl: any
  flutter:
    sdk: flutter

dev_dependencies:
  http_parser: ^4.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
